### ISSUE TITLE
Running s2m fails on Ubuntu when the new site db doesn't already exist

### ISSUE THREAD

**Issue by benlk** [INN/deploy-tools#12]
In `fablib/tools/local/__init__.py`, [`local_commands.destroy_db(env.single_blog_name)`](https://github.com/INN/deploy-tools/blob/master/fablib/wp/migrations.py#L86) will return 1 if the database doesn't already exist. Temporary solution is to comment that line out.

**Comment by rnagle** [comment]
The `s2m` command no longer exists.
