### ISSUE TITLE
Put local_fabfile.py in .gitignore

### ISSUE THREAD

**Issue by benlk** [INN/deploy-tools#21]
`fablib/wp/local_fabfile.py` is imported by the deploy tools, but it's not supposed to kept under version control. Shouldn't it be in the `.gitignore`?

**Comment by rnagle** [comment]
Yep, this happens in the [`gitignore`](https://github.com/INN/deploy-tools/blob/master/examples/gitignore#L1) file in the `examples` directory, which should be copied over to your project root upon cloning/installing the deploy tools.
